### ISSUE TITLE
no test coverage whatsoever! que tal?

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/Stride-BenchPress#3]
reader! hello! was poking around in the repo, and realized that there is no test coverage whatsoever for this application! no judgement, just a fact! But! I do think that additional feature work should be halted until we have regression tests in place for the existing features, as this a) is what we advise clients to do, and b) will provide a harness for anyone who ends up working on this thing in the future. If it's worth building a feature, it's worth testing it.

__Helpful Links to Get Started:__

- [Rails Guides: Testing](https://guides.rubyonrails.org/testing.html)

**Comment by kamok** [comment]
I've gotten the app running locally and will be adding tests

**Comment by ixjamesyoo** [comment]
Aw, Travis you've discovered the dark stain we've been covering up. Boris is also apparently in the process of writing tests, and I've started a local branch for some unit tests of the React components. Testing coming soon!

**Comment by cohesivejones** [comment]
Added request/feature specs to benchpress, however we still need to test coverage for the frontend code (i.e Redux data layer and react components). 

Also it might be worth while creating a rake task `rake spec` which runs potentially both rspec tests and javascript tests. 

And it might be worth while adding linters (such as eslint and rubocop) to force some kind of coding standard. It's always nice to run `rubocop -a` or `eslint --fix` and watch all the linting issues disappear.

**Comment by kamok** [comment]
@cohesivejones I think we can close this issue.

**Comment by cohesivejones** [comment]
This issue can now be closed
